development:
  adapter: postgresql
  encoding: utf8
  database: flapper-news-dev
  username: jamesnewman
  password: password
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: flapper-news-test
  username: jamesnewman
  password: password
  host: localhost
